### ISSUE TITLE
timestamp problem

### ISSUE THREAD

**Issue by Rolandisimo1** [dmpstats/Standardise_Formats_and_Calculate_Basic_Statistics#18]
I get this error when working with this study:
Study
331589962 / Ecology Yaguara Panama
Animals
6 Animals
Ari, Corazones, Diamante, Imama, Puma tag736533, Su

I think the problem is that some animals have 2 deployments.  

In the Movebank App I set the Attribute defining track ID = Animal 
because I want the data from the 2 deployments to be combined.

Error: Not all timestamps in `x` are ordered within track.
ℹ It is required that all record have a positive time difference compared to
  the previous one.
ℹ The first offending record is of track: Su at time: 2023-01-27 04:00:46
  (record: 24020), the next record has an earlier or equal timestamp.

**Comment by Rolandisimo1** [comment]
fyi I get the same error when I try using the 'define track ID' app before this as well.

**Comment by bcaneco** [comment]
Hi @Rolandisimo1, thanks for reaching out.

Indeed, it sounds like the issue is being caused by the data not being ordered within each track ID when multiple deployments are comprised in it. Unfortunately we don't have access to that particular study, so we are unable to reproduce that error. 

However, and incidently, we also found a similar issue yesterday with one of our datasets and we were wondering if there has been any change with the Movebank Download App, which used to order data within track ID by default.

In any case, and for safety, we will implement an ordering step in this app and have it published asap - hopefully that fixes this issue.

**Comment by bcaneco** [comment]
Hi @Rolandisimo1,

We've just published a new version of the App on MoveApps, which now enforces data to be ordered by time whithin the defined track ID, before proceeding with the remaining data processing steps.

Please let us know if that fixes the problem.

**Comment by Rolandisimo1** [comment]
Great, thanks for the quick reply, the app works well now!

**Comment by annescharf** [comment]
source of error is now also fixed, sorry for taking so long (https://github.com/movestore/Movebank-Loc-move2/commit/d81ef9f80483f2f34841369b19a9532fd22e5567)
